apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: filesystems.rook.io
spec:
  group: rook.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Cluster
    listKind: ClusterList
    plural: filesystems
    singular: filesystem
    shortNames:
      - fs
