apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: pools.rook.io
spec:
  group: rook.io
  version: v1alpha1
  scope: Namespaced
  names:
    kind: Cluster
    listKind: ClusterList
    plural: pools
    singular: pools
    shortNames:
      - pool
      