apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: gitlabs.gitlab.com
spec:
  group: gitlab.com
  version: v1beta1
  names:
    kind: GitLab
    plural: gitlabs
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            helmRelease:
              type: string
            migrationsTemplate:
              properties:
                configMapKey:
                  type: string
                configMapName:
                  type: string
              required:
              - configMapName
              - configMapKey
              type: object
            version:
              type: string
          required:
          - version
          - migrationsTemplate
          - helmRelease
          type: object
